// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/_middleware.tsx";
import * as $2 from "./routes/aula-extraescolares-ludoteca.tsx";
import * as $3 from "./routes/aula-extraescolares-sabado-en-familia.tsx";
import * as $4 from "./routes/aula-infantil.tsx";
import * as $5 from "./routes/aula-madre-de-dia.tsx";
import * as $6 from "./routes/aula-primaria.tsx";
import * as $7 from "./routes/extraescolares-2023-2024.tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/jornada-puertas-abiertas-2023.tsx";
import * as $10 from "./routes/legal-aviso-legal.tsx";
import * as $11 from "./routes/legal-politica-de-cookies.tsx";
import * as $12 from "./routes/legal-politica-de-privacidad.tsx";
import * as $13 from "./routes/mas-informacion.tsx";
import * as $14 from "./routes/quienes-somos-espacios.tsx";
import * as $15 from "./routes/quienes-somos-faqs.tsx";
import * as $16 from "./routes/quienes-somos-hegazti.tsx";
import * as $17 from "./routes/quienes-somos-proyecto.tsx";
import * as $$0 from "./islands/AnimatedMenuItem.tsx";
import * as $$1 from "./islands/AnimatedMobileMenuItem.tsx";
import * as $$2 from "./islands/CookieBanner.tsx";
import * as $$3 from "./islands/Counter.tsx";
import * as $$4 from "./islands/DesktopMenu.tsx";
import * as $$5 from "./islands/Hamburger.tsx";
import * as $$6 from "./islands/Language.tsx";
import * as $$7 from "./islands/MobileMenu.tsx";
import * as $$8 from "./islands/NavBar.tsx";
import * as $$9 from "./islands/SectionContact.tsx";
import * as $$10 from "./islands/SectionMasInformacion.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/_middleware.tsx": $1,
    "./routes/aula-extraescolares-ludoteca.tsx": $2,
    "./routes/aula-extraescolares-sabado-en-familia.tsx": $3,
    "./routes/aula-infantil.tsx": $4,
    "./routes/aula-madre-de-dia.tsx": $5,
    "./routes/aula-primaria.tsx": $6,
    "./routes/extraescolares-2023-2024.tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/jornada-puertas-abiertas-2023.tsx": $9,
    "./routes/legal-aviso-legal.tsx": $10,
    "./routes/legal-politica-de-cookies.tsx": $11,
    "./routes/legal-politica-de-privacidad.tsx": $12,
    "./routes/mas-informacion.tsx": $13,
    "./routes/quienes-somos-espacios.tsx": $14,
    "./routes/quienes-somos-faqs.tsx": $15,
    "./routes/quienes-somos-hegazti.tsx": $16,
    "./routes/quienes-somos-proyecto.tsx": $17,
  },
  islands: {
    "./islands/AnimatedMenuItem.tsx": $$0,
    "./islands/AnimatedMobileMenuItem.tsx": $$1,
    "./islands/CookieBanner.tsx": $$2,
    "./islands/Counter.tsx": $$3,
    "./islands/DesktopMenu.tsx": $$4,
    "./islands/Hamburger.tsx": $$5,
    "./islands/Language.tsx": $$6,
    "./islands/MobileMenu.tsx": $$7,
    "./islands/NavBar.tsx": $$8,
    "./islands/SectionContact.tsx": $$9,
    "./islands/SectionMasInformacion.tsx": $$10,
  },
  baseUrl: import.meta.url,
};

export default manifest;
